name: Terraform Dev Check
permissions: read-all # Allow the workflow to read the repository's content
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  terraform-checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform/
    env:
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.12.2

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Run TFLint
        uses: terraform-linters/setup-tflint@v1
      - run: tflint

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Setup Infracost
        uses: infracost/actions/setup@v2

      - name: Authenticate Infracost
        run: infracost auth login
        env:
          INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}

      - name: Run Infracost breakdown
        run: |
          infracost breakdown \
            --path=tfplan.binary \
            --terraform-plan-flags="-out=tfplan.binary" \
            --format=json \
            --out-file=infracost.json

      - name: Post cost estimate as PR comment
        if: github.event_name == 'pull_request'
        uses: infracost/actions/comment@v2
        with:
          path: infracost.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Azure Logout
        run: |
          az logout # Good practice to log out of Azure after the job completes
        if: always()
